### ISSUE TITLE
Api  request doesn't take  `error`  response into account

### ISSUE THREAD

**Issue by yupnano** [vigozhang/neb-go#1]
Hi, thank your for this excellent Golang API SDK.

I have tired [`TestApi_SendRawTransaction`](https://github.com/vigozhang/neb-go/blob/master/core/rpc/api_test.go#L73) in 'api_test.go', and found that it doesn't handle the error response properly. 

Api request has two kinds of response, take sendRawTransaction as an example:
```
//if the request is correct
{"result":{"txhash":"b015740f2af1a8f93189490a9477b612163611c5d6aaf8235be64ddfc4e35279","contract_address":""}}

//if the request has an error
{"error":"transaction's nonce is invalid, should bigger than the from's nonce"}
```

And this neb-go didn't handle the error response properly, It just return `nil` and print out an message  :
```
=== RUN   TestApi_SendRawTransaction

2018/06/22 16:58:45 SendRawTransaction error:json: cannot unmarshal string into Go value of type rpc.SendTransactionResponse, response is {"error":"transaction's nonce is invalid, should bigger than the from's nonce"}
--- FAIL: TestApi_SendRawTransaction (1.42s)
	api_test.go:103: TestApi_SendRawTransaction failed
```

**Comment by vigozhang** [comment]
Thanks for your reply.
At the beginning,I just returned the result part of response and ignore the error part. If the  response has an error,I returned nil result and also the error during parse the response, the invoker can check the error to see if the request is correct. 
I have just check the official java implementation, and it return the resullt and error in one object.I will adjust the go implementation to the same behavior.
